### ISSUE TITLE
Opening links inside Jolla2gether app broken.

### ISSUE THREAD

**Issue by RoestVrijStaal** [tace/jolla2gether#11]
Jolla2gether version: v0.18-1

1) In Jolla2gether app, go to a duplicate question (like https://together.jolla.com/question/52344/android-apps-do-not-honour-display-orientation-settings/ )

2) Go to the  answer which has the link to the similair question (in case of the example, https://together.jolla.com/question/52344/android-apps-do-not-honour-display-orientation-settings/?answer=52514#post-id-52514)

3) Try to open that link with Jolla2gether app.

4) The bug occurs. The answer which has the link to the similair question gets opened instead of the link.

**Comment by tace** [comment]
Hi sorry for the delay. And thanks for reporting. I can verify this bug. So seems opening with jolla2gether app (or with webview) does not work for any links from the answerpage. This feature got broken when separate page was done to open answers.
I check how I can fix this.
